language: go

before_install:
- cp .netrc ~/.netrc
- chmod 600 ~/.netrc

#gobuild_args: -x -ldflags "-X main.VersionString v1.2.3"

deploy:
  provider: script
  script: readme-for-projects -token=$GITHUB_TOKEN -user=jungju -repo=readme-for-projects -file=./README.md
    # - go build -o rfp
    # - ./readme-for-projects -token=$GITHUB_TOKEN -user=jungju -repo=readme-for-projects -file=./README.md
    # - cat ./README.md
  on:
    all_branches: true